### ISSUE TITLE
[Feature Request] Remove Accounts

### ISSUE THREAD

**Issue by meichthys** [powerpaul17/nc_money#10]
Currently there are 11 Accounts when first opening the app, but there doesn't seem to be a way to delete accounts.
![image](https://user-images.githubusercontent.com/10717998/195995583-678c2194-2dec-4199-866b-b48237d5a2fb.png)

**Comment by powerpaul17** [comment]
Yes, you are right, I have not implemented deleting accounts. The problem is that there can be a lot of data loss if you for example delete an account by accident so I am still thinking about the best approach here..

**Comment by meichthys** [comment]
Ok perhaps the 11 'initial' accounts I was seeing were accounts that I had setup when trying this app in the past.

A simple deletion confirmation dialog with a scary warning would probably suffice for now.

**Comment by powerpaul17** [comment]
Implemented in 666bd379fdcaaf1039a48deaed80e11ea6b64981
