### ISSUE TITLE
Importing CSV - value's not imported

### ISSUE THREAD

**Issue by pinkysworld** [powerpaul17/nc_money#12]
Hi, importing is not working for values.
It imports everything but the value is not stored.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/85413447/196175966-daa32ed7-ed23-4d36-a952-4c91fb05fbdd.png">

Could add more fields or integrate the option to add more fields?

**Comment by powerpaul17** [comment]
That's a bit difficult to debug without more information. Did you set the correct decimal separator? Can you provide me with a line from your CSV file. You can of course strip out any private information, I just want to see how it's formatted.

**Comment by pinkysworld** [comment]
Yes, I selected the correct decimal separator. I attached it for you.
[ums.CSV](https://github.com/powerpaul17/nc_money/files/9836010/ums.CSV)

**Comment by powerpaul17** [comment]
Ok, thanks for the file. I tried it and it works, I get a value of 200.00. Did you choose the "Betrag" column for both "Haben" and "Soll"? Because then the value would be 200-200=0 again...

**Comment by pinkysworld** [comment]
Haha yes I did.

**Comment by powerpaul17** [comment]
Ok, good.. 😅 But I will definitely think about improving the import dialog/workflow since there can be some confusion..
