### ISSUE TITLE
InvalidSignatureException

### ISSUE THREAD

**Issue by meyerchak** [powerpaul17/nc_money#14]
Hello Powerpaul17

In the the last two money versions, Nextcloud is saying 
"Some files have not passed the integrity check".

Thank you for your continued development for this great app!

I really enjoy having personal finance added to Nextcloud :smile:

Best Regards

Cheers

![nextcloud money](https://user-images.githubusercontent.com/8461530/196294071-5a3739aa-ad4f-4dc9-bfc8-e94c22c43fce.png)

**Comment by powerpaul17** [comment]
Yes, that's a known problem for now. I still haven't figured out a good way to do that in my build/release setup. :slightly_frowning_face:

**Comment by oswaldo-be** [comment]
Thank you for looking into it

**Comment by powerpaul17** [comment]
Yeah, unfortunately I haven't figured it out yet.. :slightly_frowning_face:

**Comment by powerpaul17** [comment]
But the releases in the app store are signed with my key, so that's working at least.. :wink:

**Comment by adam-wolak** [comment]
After updating Nextcloud to 25.0.3 problem is the same. Removing Money did not make any change. Application was installed from app store.

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- money
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature could not get verified.

Raw output
==========
Array
(
    [money] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature could not get verified.
                )

        )

)

**Comment by powerpaul17** [comment]
As I said, this is a known issue as I haven't figured out how to correctly create the signatures in my development setup yet..

**Comment by powerpaul17** [comment]
Should be fixed with bd28caf49e56523a624320013fca7fdbcabbc4a8
