### ISSUE TITLE
l10n - string meaning explanation (please)

### ISSUE THREAD

**Issue by p-bo** [powerpaul17/nc_money#15]
Hi, to be able to translate it correctly according its meaning, this newly added string – would it be possible to give some hint regarding it please? Thanks :-)
![obrazek](https://user-images.githubusercontent.com/12208593/197146901-d594a6e2-df30-474b-b998-0d45ba7d326e.png)

**Comment by powerpaul17** [comment]
Sure, it is an abbreviation of 'month', in the context of 'per month'. I search the documentation but it states that in Vue components it is not possible to provide a hint for translators :disappointed: Or do you know if it's possible? Maybe @rakekniven knows something?

**Comment by p-bo** [comment]
Thanks, added as comment to string on Transifex for other translators:
![obrazek](https://user-images.githubusercontent.com/12208593/197157133-542d7094-2b09-4a81-bef1-c03268a9a006.png)

**Comment by p-bo** [comment]
Regarding Developer notes section, in case of strings originating from .vue files, it is used to help to identify them:

"Big improvements on locating strings based in vue files.

The script doing the string preparation of vue files is writing a comment as “DEVELOPER NOTES”. There you find the file and code line."

Source:
https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550
(near the end of the first post)

**Comment by powerpaul17** [comment]
Yeah, this is really a limitation. Because apps will mostly use .vue components in the future. Would be nice to find a way to include translator information here..

**Comment by p-bo** [comment]
Maybe what about to start thread regarding this in https://help.nextcloud.com/c/translations/23 ?
(quickly checked searching term vue there and it seems it wasn't discussed in this space yet)

**Comment by p-bo** [comment]
@powerpaul17 it seems, that solution was proposed already:
https://github.com/nextcloud/docker-ci/pull/268

**Comment by punkyard** [comment]
l10n FR
french translation is not complete

assets = actif
liabilities = passif
equity = capitaux propres
unbalanced = résultat / or / entrées non soldées

![moneu l10n](https://user-images.githubusercontent.com/59349105/199987420-77bc08ef-b88b-4a54-90ce-149462bc2691.png)

**Comment by punkyard** [comment]
https://www.transifex.com/nextcloud/nextcloud/translate/#fr/money/439273869?q=reviewed%3Ano

404, no page there ..

**Comment by punkyard** [comment]
https://www.transifex.com/nextcloud/nextcloud/translate/#fr/money/439273861
i worked it around 👍
