### ISSUE TITLE
dark theme display error

### ISSUE THREAD

**Issue by punkyard** [powerpaul17/nc_money#21]
nc 2407
same on safari and chrome

![money dark](https://user-images.githubusercontent.com/59349105/199994977-44a1ef31-22ba-430e-bf4b-30c73da070cc.png)

![money dark sel](https://user-images.githubusercontent.com/59349105/199995458-6f1e6753-5e72-47f1-981e-0b4ea9977a3f.png)

**Comment by powerpaul17** [comment]
On NC 24 there should be no issue, I tested on Chrome (don't have Safari unfortunately), for NC 25 I have prepared a fix for dark mode but it is not pushed and released yet.

**Comment by punkyard** [comment]
there shouldn't, but there is .. see?
in my first picture, the white frame vanishes the white texts
in the second picture, i did a Ctrl+A, to make every text visible

**Comment by powerpaul17** [comment]
I released 0.10.0 today, could you please try if the problem still exists?

**Comment by punkyard** [comment]
hi,
nothing has changed on my side.
Money does not offer any updates in my app list.

**Comment by punkyard** [comment]
in the app store it says v0.9.0
https://apps.nextcloud.com/apps/money

**Comment by punkyard** [comment]
on nc_money it reads v0.9.0 too
https://github.com/powerpaul17/nc_money

**Comment by powerpaul17** [comment]
Yes, you're right.. I meant 0.9.0 which is the latest version.. 😅

**Comment by punkyard** [comment]
that's the version I have, nothing's changed

**Comment by powerpaul17** [comment]
Does the problem still exist in 0.11.3? It's only available for NC 25 though..

**Comment by punkyard** [comment]
Hi, i had to update to 25, so i won't be able to tell you.
But i do miss Dark Breeze ..

**Comment by powerpaul17** [comment]
I meant, is it gone now in NC 25 on version 0.11.3? Or does the problem still persist? :slightly_smiling_face:

**Comment by punkyard** [comment]
update to NC 25 indicated that Dark Breeze was not compatible, and it was deactivated during update. So i'm not using it since the update. Then i can't tell you how it looks now.
Have I understood your question and answered to it?

**Comment by powerpaul17** [comment]
Ok, now I understand, you are using something else called "Dark Breeze". That would have been important to know from the beginning.. :sweat_smile: I thought standard dark mode of NC is broken for you..

**Comment by punkyard** [comment]
oh my ! I'm really sorry for the confusion.
I've tried to inform both (dark theme and dark breeze)
please apologise
