### ISSUE TITLE
Not working with NC 25

### ISSUE THREAD

**Issue by olla-dev** [powerpaul17/nc_money#29]
App installs fine, I can see the main menu. But all server requests fail.

**Comment by powerpaul17** [comment]
Hello, can you please give more details. What requests fail and with what status code? Can you check the response? Do you have any server logs of the failed request?

**Comment by olla-dev** [comment]
I saw a HTTP 500 for /apps/money/accounts
also there is no button to add an account (it should be in the settings section no?)

**Comment by R7JANV1** [comment]
I get the following message when I open /apps/money/accounts

Access denied
CSRF check failed

**Comment by powerpaul17** [comment]
That does not seem to be related to the app.. you do open it in the browser, right? Currently there is no API available.. do you have access to the server logs?

**Comment by R7JANV1** [comment]
> That does not seem to be related to the app.. you do open it in the browser, right? Currently there is no API available.. do you have access to the server logs?

Yes.

**Comment by R7JANV1** [comment]
Maybe a problem with Nextcloud AIO? @szaimen

**Comment by szaimen** [comment]
Hm... I dont think so. Also please refrain from pinging me for specific apps. I am not responsible for these.

**Comment by FunkyWonder** [comment]
I was wondering if there was any progress on this issue because I'm having the exact same issue.
The exact error code is:

**192.168.30.60 - - [22/Aug/2023:20:00:32 +0000] "GET /apps/money/accounts HTTP/1.1" 500 4492 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"**

The result of this is that i don't have the account button.
I'm currently running this version of nextcloud with the latest tag specified: https://github.com/nextcloud/docker

Thanks for the answer!

**Comment by powerpaul17** [comment]
Without a server log it's impossible for me to find out what's causing an error 500.

**Comment by FunkyWonder** [comment]
The server log is as follows:

`{"reqId":"3G8LSBMuzXRvbv2hSuut","level":3,"time":"2023-08-22T19:45:52+00:00","remoteAddr":"192.168.30.60","user":"nate","app":"index","method":"GET","url":"/apps/money/accounts","message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near \"FROM\": syntax error","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","version":"27.0.2.1","exception":{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near \"FROM\": syntax error","Code":1,"Trace":[{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":295,"function":"wrap","class":"OC\\DB\\Exceptions\\DbalException","type":"::","args":[["Doctrine\\DBAL\\Exception\\SyntaxErrorException"]]},{"file":"/var/www/html/custom_apps/money/lib/Controller/AccountController.php","line":44,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getAccounts","class":"OCA\\Money\\Controller\\AccountController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Money\\Controller\\AccountController","getAccounts",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["money.account.get_accounts"]]},{"file":"/var/www/html/lib/base.php","line":1071,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/money/accounts"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/DB/Exceptions/DbalException.php","Line":71,"Previous":{"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near \"FROM\": syntax error","Code":1,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1814,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\SQLite\\ExceptionConverter","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],["Doctrine\\DBAL\\Query"]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1749,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],["Doctrine\\DBAL\\Query"]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1055,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],"SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[]]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = :user_id GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":293,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/custom_apps/money/lib/Controller/AccountController.php","line":44,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getAccounts","class":"OCA\\Money\\Controller\\AccountController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Money\\Controller\\AccountController","getAccounts",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["money.account.get_accounts"]]},{"file":"/var/www/html/lib/base.php","line":1071,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/money/accounts"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php","Line":71,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[HY000]: General error: 1 near \"FROM\": syntax error","Code":1,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","line":65,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args":[["PDOException",["HY000",1,"near \"FROM\": syntax error"]]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1042,"function":"prepare","class":"Doctrine\\DBAL\\Driver\\PDO\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\""]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = :user_id GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":293,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/custom_apps/money/lib/Controller/AccountController.php","line":44,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getAccounts","class":"OCA\\Money\\Controller\\AccountController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Money\\Controller\\AccountController","getAccounts",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["money.account.get_accounts"]]},{"file":"/var/www/html/lib/base.php","line":1071,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/money/accounts"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":30,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY000]: General error: 1 near \"FROM\": syntax error","Code":"HY000","Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","line":60,"function":"prepare","class":"PDO","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\""]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1042,"function":"prepare","class":"Doctrine\\DBAL\\Driver\\PDO\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\""]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":262,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = ? GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[],null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":345,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"a\".*, EXTRACT(YEAR FROM c.date) AS \"year\", EXTRACT(MONTH FROM c.date) AS \"month\", SUM(b.value) AS \"balance\" FROM \"oc_money_accounts\" \"a\" LEFT JOIN \"oc_money_splits\" \"b\" ON b.dest_account_id = a.id LEFT JOIN \"oc_money_transactions\" \"c\" ON b.transaction_id = c.id WHERE a.user_id = :user_id GROUP BY EXTRACT(YEAR FROM c.date), EXTRACT(MONTH FROM c.date), \"a\".\"id\"",["nate"],[]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":280,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":293,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/custom_apps/money/lib/Controller/AccountController.php","line":44,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getAccounts","class":"OCA\\Money\\Controller\\AccountController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Money\\Controller\\AccountController"],"getAccounts"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Money\\Controller\\AccountController","getAccounts",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["money.account.get_accounts"]]},{"file":"/var/www/html/lib/base.php","line":1071,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/money/accounts"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","Line":60}}},"CustomMessage":"--"}}`

**Comment by powerpaul17** [comment]
Thanks for the log, which DB are you using?

**Comment by FunkyWonder** [comment]
I'm currently using SQLite but I was planning to switch to a different database since it's pretty slow

**Comment by powerpaul17** [comment]
Oh, ok. I never tested with SQLite.. :sweat_smile: but it sounds probable that something is not compatible..

**Comment by powerpaul17** [comment]
Perfect! I'll try to set PostgreSQL or MySQL as a required dependency somewhere. Thanks for the kind words, I don't have enough time for all the nice features sadly.. :slightly_frowning_face:
