### ISSUE TITLE
Missing quotes.js

### ISSUE THREAD

**Issue by codejp3** [powerpaul17/nc_money#3]
I know this is a NC 11 App, but it looks so promising to potentially be THE BEST financial software tool for my 64 year old mother and the NC 12 server I'm setting up for her that I decided to give it a try.

First issue encountered, which I don't believe the NC11/12 version conflict being the cause of it.

`Refused to execute script from 'https://LAN_IP/apps/money/js/services/quotes.js?v=RAND_NONCE_VER_STRING' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Checked and sure enough, no /apps/money/js/services/quotes.js file exists.

**Comment by powerpaul17** [comment]
Hello. Firstly, thanks for the compliments, I would not say, it's "the best" financial software but currently the only one.. ;)

Unfortunately I was not able to finish the first version because I currently have a lot of work to do. There is still a big problem with the html templates as in Chrome there is no transaction view visible at the moment. I would like to fix this soon.

Additionally there are still a lot of performance issues and other minor problems which make the user experience less than ideal..

**Comment by powerpaul17** [comment]
The problem you mentioned was due to a missing file, should be corrected now. I pushed some changes but the Chrome problem still persists.

**Comment by codejp3** [comment]
FYI, NC_Money has other issues that keep it from working properly on NC 12. I only made a support thread for the missing file because that issue seemed to affect NC 11 installs too. I'm going to look into some of the NC 12 compatibility issues.....but in the meantime, I'm setting up a NC 11 test environment as we speak. I don't know much of anything about coding for NC and its' API, but I do know web-centered code. I'm going to see if I can knock out the Chrome issue for you since that seems to be one of your biggest hurdles/burdens right now. Maybe I can help take that one off your plate, and then you can focus on NC 12 compatibility and new features (I have a few in mind).

Thank you for your time and effort thus far! My mom is allergic to technology and can't use anything cluttered/complex. Until NC-Money works for NC 12, I'm currently using GNUCash and just sync the data with NC. The GNUCash interface is on the complex side for her AND I don't have a way for her to edit her finances through NC, which I'm trying to setup as THE GO-TO place for her to do anything and everything she wants. Due to these deficiencies, I looked elsewhere and saw your NC-Money AP. It fits the bill for her PERFECTLY. Non-cluttered interface, and in-cloud editing. That's why I'd really like to see this thing polished up and setup for long-term success. Thanks again!
