### ISSUE TITLE
NC 27 not supported

### ISSUE THREAD

**Issue by MaxGeneris** [powerpaul17/nc_money#48]
Hi Paul,

I upgraded today to NextCloud 27.0.0 RC4 and the app is not supporting it. 

Would you mind updating it?

Thank you so much!

**Comment by powerpaul17** [comment]
I didn't have time to test on NC 27 but you should be able to enable it anyway through a button click if I'm not mistaken.

**Comment by MaxGeneris** [comment]
Yeah, I know that I can enable it. Unfortunately it needs your supervision as it only show the main account groups but no accounts underneath. 
<img width="281" alt="image" src="https://github.com/powerpaul17/nc_money/assets/133965749/674f8734-27d2-4416-8952-37a5e0058f22">

**Comment by powerpaul17** [comment]
Yeah, I changed that. If you click on the account type, the list is shown in the main view.. I wanted to free up the navigation bar. 😉

**Comment by powerpaul17** [comment]
I assume it is working for you now..?

**Comment by oswaldo-be** [comment]
But nextcloud still shows it as incompatible with 27.
So I can ignore this and just update?

**Comment by powerpaul17** [comment]
Yes you can probably ignore and update. I'll prepare a new release for NC 27 soon.
