### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by untuonac** [powerpaul17/nc_money#52]
Hi all,

Sorry for the banal question, i ask for help kindly to change the language.

In the "Settings" menu there is only the item "Show inverted income/liability account balances".

I tried to move by translating the items present in the files en_gb.js en_gb.json of the directory ../money/l10n without success.

Maybe it's easier than expected.

Thanks in advance,
Raffaele.

**Comment by powerpaul17** [comment]
Hello. The app uses the language which is set in the Nextcloud settings. But it falls back to english if the translation does not exist.

**Comment by untuonac** [comment]
> @untuonac Is this fixed for you?

Hi,
I completed the translation of the two files locally (Italian) and works properly but for each update of the app, if the files are not also changed to the repository, it returns to the original language.

**Comment by powerpaul17** [comment]
Ok, so the problem are missing italian translations :slightly_smiling_face:  The app is translated using transifex, if you want you can contribute your translations there. Or you can send me your patches, either by making a PR or post it here and I can incorporate them into the repository. Then also others can benefit from it..
