### ISSUE TITLE
Graphical error in dashboard card

### ISSUE THREAD

**Issue by JannikWilhelm** [powerpaul17/nc_money#53]
**Describe the bug**
After upgrade to Version 0.21.0 the dashboard card no longer works.
The balances of all 3 graphs are 0 for all points.
Also the lines are offset downwards extremely (about 2 cards high per line) and not respecting the card borders.

**To Reproduce**
1. Update of nc money to latest version via app store
2. reload

**Expected behavior**
All 3 graphs should be inside the card applet and displaying the corresponding values

**Screenshots**
![grafik](https://github.com/powerpaul17/nc_money/assets/32778935/cebf7011-8175-407e-ac61-51aca992e263)
![grafik](https://github.com/powerpaul17/nc_money/assets/32778935/de582921-1189-4a84-a736-561370913ac5)

**Nextcloud information (please complete the following information):**
 - Nextcloud version: NC Hub 6 (27.1.1)
 - App version:  docker image
 - PHP version: inside nc docker image
 - Database type and version: mariadb 10.7

**Desktop (please complete the following information):**
 - OS: Fedora 38 Workstation
 - Browser Firefox
 - Version 118

**Comment by JannikWilhelm** [comment]
docker-compose.yml contents

<details><summary>Details</summary>
<p>

version: '3'
 
services:
  db:
    image: mariadb:10.7
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /home/dock/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=REDACTED
      - MYSQL_PASSWORD=REDACTED
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=REDACTED
    restart: unless-stopped
 
  app:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    links:
      - db
    volumes:
      - /nextcloud/nextcloud:/var/www/html
      - /nextcloud/apps:/var/www/html/custom_apps
      - /nextcloud/config:/var/www/html/config
      - /nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=REDACTED
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=REDACTED
      - MYSQL_HOST=db
    restart: unless-stopped

</p>
</details>

**Comment by powerpaul17** [comment]
Thanks for the bug report. I can reproduce the problem and will find a fix :slightly_smiling_face:

**Comment by powerpaul17** [comment]
Fixed in 77e43fac416a2927712f417e39e29853973a7825, I'll do a patch release tomorrow
