### ISSUE TITLE
Display error Account List

### ISSUE THREAD

**Issue by SafetyIng** [powerpaul17/nc_money#56]
In the account list, a blank line with Litst Item Bubble appears next to the placeholder.

**Screenshots**
![image](https://github.com/powerpaul17/nc_money/assets/77867539/7a805939-4ce6-4cd7-977a-92a140a2469c)

**Nextcloud information (please complete the following information):**
 - Nextcloud version: 27.1.2
 - App version: 0.22.1

**Desktop (please complete the following information):**
 - OS: MS Windows 10
 - Browser: chrome
 - Version 118.0.5993.70

**Comment by powerpaul17** [comment]
Thanks for the bug report! 🙁  Fixed in 48dd9e6f676c178a571ef5cbcccacafc86b0e09a.
