### ISSUE TITLE
Improve mobile handling

### ISSUE THREAD

**Issue by SafetyIng** [powerpaul17/nc_money#58]
The app is not really mobile friendly. 
![image](https://github.com/powerpaul17/nc_money/assets/77867539/0d71c719-3032-4d35-a4bf-86185e9f4a81)

Idea for improvement: 
The currently collapsed fields can then be hidden with the hide/display button (like the current individual bookings); here, for example, as in DataTables.js ( https://datatables.net/extensions/responsive/ )
![image](https://github.com/powerpaul17/nc_money/assets/77867539/c03a63a6-20cf-45ae-95ef-2e042d85de2e)

You could also show the elements via a modal or a side menu (as with data or the calendar).

**Comment by powerpaul17** [comment]
I'm aware that mobile view is basically unusable. It is already work in progress but I haven't had time to finish it. The splits will go into the sidebar as you described. It is also recommended by Nextcloud's design principles.

**Comment by SafetyIng** [comment]
No rush! I sometimes have ideas like that. Unfortunately, I am currently 0.0 versed in vue, so I can only provide support on this basis. Maybe it's about time for me

**Comment by powerpaul17** [comment]
Implemented in 308232fa9f47b5d6457902bdb2ed4aeb82914523
