### ISSUE TITLE
Processing of currencies with decimal comma or point

### ISSUE THREAD

**Issue by SafetyIng** [powerpaul17/nc_money#59]
Currently you can only enter amounts with a decimal point. For German-speaking countries, it would make sense to switch to decimal points. Either that a comma is taken into account when entering or that you can generally change over. 

For example, if I enter 2.55, I get 2.00 as the value after leaving the field.
![image](https://github.com/powerpaul17/nc_money/assets/77867539/6b0e847a-fe37-4506-a189-7df078178da8)
After processing:
![image](https://github.com/powerpaul17/nc_money/assets/77867539/3163251d-5881-43fb-8224-adab5520f725)

**Comment by powerpaul17** [comment]
Thanks for your report. It is intended to work like you described but apparently there was a bug introduced. I'll investigate and try to fix it.

**Comment by powerpaul17** [comment]
Should be fixed in 569151dc7548dc262c1cea8142e9b404f9f877fe
