### ISSUE TITLE
Multiple Companies / Sections

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [powerpaul17/nc_money#62]
It would be nice if there would be a possibility to have multiple companies / business units /section.
For each section it should be possible to add its own accounts,... 
So instead of a list of accounts i would recommend:

company
  - account a
  - account b
  - ....

**Comment by powerpaul17** [comment]
Thanks for the suggestion. I'm already working on it.. 😉

**Comment by GVLLIFESTYLE** [comment]
Perfect
-------- Ursprüngliche Nachricht --------Von: Paul Tirk ***@***.***> Datum: 08.01.24  18:35  (GMT+01:00) An: powerpaul17/nc_money ***@***.***> Cc: GVL ***@***.***>, Author ***@***.***> Betreff: Re: [powerpaul17/nc_money] Multiple Companies / Sections (Issue #62) 
Thanks for the suggestion. I'm already working on it.. 😉

**Comment by powerpaul17** [comment]
Completet in 82e45ba57134cb1faba7d2a5b790b56ce5f9d4b2
