### ISSUE TITLE
Link to existing gnucash file synced to nextcloud

### ISSUE THREAD

**Issue by mattheweigand** [powerpaul17/nc_money#63]
I'm trying to get into gnucash and, like most of my files, the gnucash file is synced to nextcloud already. I'd love to be able to simply select the file with nc_money and have nc_money display the values in the file.

It doesn't have to even be able to edit the file, just use it as a source for displaying data.

**Comment by powerpaul17** [comment]
Hello, although I base the apps concept a bit on Gnucash, the app itself has nothing to do with it. What you want would be some kind of Gnucash-Viewer-App which is really out of scope here.
