### ISSUE TITLE
Dashboard book links to wrong url

### ISSUE THREAD

**Issue by moolicc** [powerpaul17/nc_money#67]
**Describe the bug**
On the dashboard widget, a book's item in the summary listing here links to "/extra-apps/money/books/[bookid]", but when I navigate to the book through the money app, the url is "/index.php/apps/money/book/#/[bookid]"

**To Reproduce**
1. Add Money to your dashboard
2. Add a book to the Money app
3. Attempt to navigate to the book from the dashboard widget

**Expected behavior**
Redirection to the book

**Screenshots**
**Expected**:
![image](https://github.com/powerpaul17/nc_money/assets/28231505/0af5e2f9-19b5-42b0-ae53-2f12f5d7e3d9)

**Actual**:
![image](https://github.com/powerpaul17/nc_money/assets/28231505/66755e16-0f56-4d98-b03e-62c6f46dc4ca)

**Nextcloud information (please complete the following information):**
 - Nextcloud version: 27.1.9
 - App version: 0.25.1
 - PHP version: 8.2.18
 - Database type and version: mysql, 8.0.37

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge and Firefox
 - Versions: 124, 126

**Additional context**
Not really context per-se, but a very tiny nit-pick. There are scroll-bar arrows on this dashboard widget, but they default to hidden for dashboards for other apps.

**Comment by powerpaul17** [comment]
Hello and thanks for the bug report. I fixed it in 54324af067f4ae19e91c6c27213a2c36635a66ec

**Comment by moolicc** [comment]
@powerpaul17, sweet! Thanks for your prompt work on this project!

**Comment by powerpaul17** [comment]
You're welcome. It was a small thing and easily fixable :wink:
