### ISSUE TITLE
Updates to transactions after they've been created have no effect

### ISSUE THREAD

**Issue by bMorgan01** [powerpaul17/nc_money#69]
Thank you for your effort! There's tons of potential here. I noticed something small:

**Describe the bug**
Creating an expense transaction then later editing it does not update left sidebar nor overview charts.

**To Reproduce**

1. Create a book
4. Create an expense account
5. Apply a small transaction to the new expense account ($1000)
6. After the expense has been created, reopen the expense and change the amount to ($1200)
7. See that the sidebar value for 'Expenses' has not been updated to show new value.

**Expected behavior**
'Expenses' for this book should be $1200, but instead the app displays $1000

**Screenshots**
![image](https://github.com/powerpaul17/nc_money/assets/27574085/91ef511f-08a2-4de7-8f73-89d72c41aa7b)

**Nextcloud information (please complete the following information):**

- Nextcloud version: Snap 27.1.9
- App version: 0.26.1
- PHP version: 8
- Database type and version: mysql (I think?)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Firefox
- Version: 0.26.1 (64-bit)

**Comment by powerpaul17** [comment]
You're right. It worked before but I migrated to Vue 3 and it seems to be broken now. I'll have a look at it.

**Comment by powerpaul17** [comment]
Should be fixed now with 1c0279c63bc082cb6f3c43548b9d8640c4b7e58f
