### ISSUE TITLE
Transaction on the first of the month is applied the month before

### ISSUE THREAD

**Issue by bMorgan01** [powerpaul17/nc_money#71]
**Describe the bug**
Date set to Oct. 1
![image](https://github.com/powerpaul17/nc_money/assets/27574085/0bf61e3c-51ca-4163-a43a-70a776b8afb7)
Date set to Oct. 2
![image](https://github.com/powerpaul17/nc_money/assets/27574085/c11060ef-51ef-4e00-8cac-2e5e37bb9741)

Note other strange behavior like this:
![image](https://github.com/powerpaul17/nc_money/assets/27574085/2b30a831-afef-49be-9029-c5307e09d4e2)
The date field does not match the date picker.

**To Reproduce**

1. Create a transaction
2. Set the date do the first of any month
3. Apply some cost to one side of a split
4. Watch the graph

**Expected behavior**
Transactions on Oct. 1 should be applied to October

**Screenshots**
See above

**Nextcloud information (please complete the following information):**

    Nextcloud version: Snap 27.1.9
    App version: 0.26.1
    PHP version: 8
    Database type and version: mysql (I think?)

Desktop (please complete the following information):

    OS: Win 10
    Browser: Firefox
    Version: 0.26.1 (64-bit)

**Additional context**
Maybe related to https://github.com/powerpaul17/nc_money/issues/68

**Comment by powerpaul17** [comment]
Hello and thanks for the detailed bug report. I think this is related to #68 and I already released 0.26.2 where it should be fixed. Could you try it after updating please?
