### ISSUE TITLE
Can no longer add transactions in new release.

### ISSUE THREAD

**Issue by cathray** [powerpaul17/nc_money#72]
**Describe the bug**
When trying to add a new transaction after clicking the + Button the progress animation is shown forever and the transaction is not being added.  The console shows the error message: "TypeError: r.getFullYear is not a function"

**To Reproduce**

1. Go to any account's transaction list.
2. Fill in the input boxes for a new transaction
3. click the + button to add the new transaction

**Expected behavior**
I expected the transaction to be added to the list of transactions.

**Screenshots**
![Ekrankopio de 2024-06-09 17-47-46](https://github.com/powerpaul17/nc_money/assets/99600873/5596e72e-422d-40be-89b7-ecc9edc18ae9)

**Nextcloud information (please complete the following information):**

- Nextcloud version: Nextcloud Hub 8 (29.0.2)
- App version: 0.26.3
- PHP version: 8.1.2
- Database type and version: PostgreSQL 14.12

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 126.0.1

**Comment by cathray** [comment]
I found the following:

- splitService.addSplit calls transactionStore.getById.
- transactionStore.getById returns a (promise) Transaction which has a date of type string (stores/transactionStore.ts line 182).
- addSplit then passes that date to accountStore.addValue unchanged so as type string (services/splitService.ts line 36).
- accountStore.addValue however assumes it is of type date and calls getFullYear on it (stores/accountStore.ts line 211ff).

**Comment by cathray** [comment]
Also the transaction gets added to the other account with only half the transaction:
![Ekrankopio de 2024-06-09 18-29-01](https://github.com/powerpaul17/nc_money/assets/99600873/58e4154c-c884-48e5-8c36-fd1ddbb35009)

**Comment by powerpaul17** [comment]
Yeah, sorry, I forgot this occurrence while fixing the time zone issues. I really should add more tests.. :sweat:

**Comment by powerpaul17** [comment]
Should be fixed in 54155604deca7b13b53092890ec5f5cdfc248f13

**Comment by powerpaul17** [comment]
And thanks for the detailed bug report! :slightly_smiling_face:
