### ISSUE TITLE
[I18N] Import transactions

### ISSUE THREAD

**Issue by meskobalazs** [powerpaul17/nc_money#8]
There is this field here:

https://github.com/powerpaul17/nc_money/blob/84c50648a6831a9bcd7fd58cdf0a3e20b4265ecb/src/components/TransactionImportDialog.vue#L52

As far as I can see, this sets the used _decimal separator_ (point or comma). So I recommend naming it as such.

**Comment by powerpaul17** [comment]
You are right, my mistake I'm not a native english speaker though.. :wink:
