### ISSUE TITLE
Google Chrome, Safari - file import not working

### ISSUE THREAD

**Issue by pinkysworld** [powerpaul17/nc_money#9]
Hi,
I'm using the latest Money App and noticed the csv import is not working. I tried it on OSX with Google chrome and Safari.
Tried drag n drop and the file selector - nothing happens.
Let me know if you need more information.

**Comment by powerpaul17** [comment]
Sorry for the late reply.. good to know, I only use Firefox. I'll check on Chrome and come back to you if I need more info..

**Comment by pinkysworld** [comment]
> Sorry for the late reply.. good to know, I only use Firefox. I'll check on Chrome and come back to you if I need more info..

Hi, I tried it on Firefox as well. it is not working.

I am using OSX Ventura 13.0 and the latest firefox/chrome/safari.

**Comment by pinkysworld** [comment]
https://user-images.githubusercontent.com/85413447/195869529-9a4e3c31-831d-4ff5-b3e0-82cc746ef5ff.mov

I created a short movie for you.

**Comment by powerpaul17** [comment]
Thanks a lot for the video. Now I understand.. :sweat_smile: You have to select the columns first. But I'll have to make it clearer in the dialog or improve the workflow..
